name: Terraform Security Checks

on:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  security:
    name: DevSecOps CI
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v4

      - name: 🧱 Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: 🧼 Terraform Init
        run: terraform init

      - name: 🔍 Terraform Validate
        run: terraform validate

      - name: 📏 Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      - name: 📏 Run TFLint
        run: tflint --recursive

      - name: 🛡️ Install Checkov
        run: pip install checkov

      - name: 🔐 Run Checkov
        run: checkov -d .
